import React from 'react';
import { useResumeData } from '../hooks/useResumeData';
import { ArrowLeft, Printer, Layout } from 'lucide-react';
import { Link } from 'react-router-dom';

export const Preview: React.FC = () => {
    const { data, updateTemplate } = useResumeData();

    const templates: Array<{ id: 'classic' | 'modern' | 'minimal'; label: string }> = [
        { id: 'classic', label: 'Classic' },
        { id: 'modern', label: 'Modern' },
        { id: 'minimal', label: 'Minimal' }
    ];

    const hasEducation = data.education.length > 0 && data.education.some(e => e.school);
    const hasExperience = data.experience.length > 0 && data.experience.some(e => e.company);
    const hasProjects = data.projects.length > 0 && data.projects.some(p => p.name);
    const hasSkills = data.skills.length > 0;

    // Template Renderers
    const renderClassic = () => (
        <div className="bg-white w-full max-w-[800px] aspect-[1/1.41] shadow-2xl p-16 font-serif text-black overflow-hidden flex flex-col mx-auto">
            {/* Header */}
            <div className="text-center mb-10 border-b-2 border-black pb-8">
                <h1 className="text-4xl uppercase tracking-tighter mb-4 m-0">{data.personalInfo.fullName || 'YOUR NAME'}</h1>
                <div className="flex justify-center gap-6 text-[11px] uppercase tracking-widest font-sans font-bold">
                    {data.personalInfo.email && <span>{data.personalInfo.email}</span>}
                    {data.personalInfo.phone && <span>• {data.personalInfo.phone}</span>}
                    {data.personalInfo.location && <span>• {data.personalInfo.location}</span>}
                </div>
            </div>

            {/* Summary */}
            {data.summary && (
                <div className="mb-8">
                    <h3 className="text-[12px] font-sans font-black uppercase tracking-widest border-b border-black mb-4 pb-1">Professional Summary</h3>
                    <p className="text-[12px] leading-relaxed italic opacity-90 text-justify">{data.summary}</p>
                </div>
            )}

            {/* Experience */}
            {hasExperience && (
                <div className="mb-8">
                    <h3 className="text-[12px] font-sans font-black uppercase tracking-widest border-b border-black mb-4 pb-1">Experience</h3>
                    {data.experience.map((exp, i) => exp.company && (
                        <div key={i} className="mb-6">
                            <div className="flex justify-between font-bold text-[12px] mb-1 uppercase">
                                <span>{exp.company}</span>
                                <span>{exp.date}</span>
                            </div>
                            <div className="italic text-[12px] mb-2">{exp.role}</div>
                            <p className="text-[11px] opacity-80 leading-relaxed whitespace-pre-wrap">{exp.description}</p>
                        </div>
                    ))}
                </div>
            )}

            {/* Education */}
            {hasEducation && (
                <div className="mb-8">
                    <h3 className="text-[12px] font-sans font-black uppercase tracking-widest border-b border-black mb-4 pb-1">Education</h3>
                    {data.education.map((edu, i) => edu.school && (
                        <div key={i} className="flex justify-between items-baseline mb-2 text-[12px]">
                            <div><span className="font-bold uppercase">{edu.school}</span> • {edu.degree}</div>
                            <span className="font-bold text-[10px]">{edu.date}</span>
                        </div>
                    ))}
                </div>
            )}

            {/* Simple footer for all */}
            <div className="mt-auto pt-8 border-t border-gray-100 text-[8px] text-center opacity-30">
                AI Resume Builder — Generated by KodNest
            </div>
        </div>
    );

    const renderModern = () => (
        <div className="bg-white w-full max-w-[800px] aspect-[1/1.41] shadow-2xl p-16 font-sans text-black overflow-hidden flex flex-col mx-auto">
            {/* Hero Header */}
            <div className="mb-12">
                <h1 className="text-5xl font-black uppercase tracking-tight m-0 mb-3 text-red-900">{data.personalInfo.fullName || 'YOUR NAME'}</h1>
                <div className="flex gap-4 text-[10px] font-bold text-gray-400 uppercase tracking-widest">
                    <span>{data.personalInfo.email}</span>
                    <span>/</span>
                    <span>{data.personalInfo.phone}</span>
                    <span>/</span>
                    <span>{data.personalInfo.location}</span>
                </div>
            </div>

            <div className="grid grid-cols-[1fr_2fr] gap-12 flex-1">
                <div className="flex flex-col gap-10">
                    {/* Summary Sidebar */}
                    {data.summary && (
                        <div>
                            <h3 className="text-[10px] font-black uppercase tracking-[0.2em] mb-4 text-red-900">About Me</h3>
                            <p className="text-[11px] leading-relaxed text-gray-600">{data.summary}</p>
                        </div>
                    )}

                    {/* Skills Sidebar */}
                    {hasSkills && (
                        <div>
                            <h3 className="text-[10px] font-black uppercase tracking-[0.2em] mb-4 text-red-900">Competencies</h3>
                            <div className="flex flex-col gap-2">
                                {data.skills.map((s, i) => (
                                    <span key={i} className="text-[10px] font-bold uppercase py-1 border-b border-gray-100">{s}</span>
                                ))}
                            </div>
                        </div>
                    )}
                </div>

                <div className="flex flex-col gap-10">
                    {/* Experience Main */}
                    {hasExperience && (
                        <div>
                            <h3 className="text-[10px] font-black uppercase tracking-[0.2em] mb-6 text-red-900 border-l-4 border-red-900 pl-4">Professional History</h3>
                            {data.experience.map((exp, i) => exp.company && (
                                <div key={i} className="mb-8 last:mb-0">
                                    <div className="text-[12px] font-black uppercase">{exp.company}</div>
                                    <div className="text-[11px] font-bold text-red-800 mb-2">{exp.role} — {exp.date}</div>
                                    <p className="text-[11px] text-gray-600 leading-relaxed">{exp.description}</p>
                                </div>
                            ))}
                        </div>
                    )}

                    {/* Projects Content */}
                    {hasProjects && (
                        <div>
                            <h3 className="text-[10px] font-black uppercase tracking-[0.2em] mb-6 text-red-900 border-l-4 border-red-900 pl-4">Signature Projects</h3>
                            {data.projects.map((proj, i) => proj.name && (
                                <div key={i} className="mb-6 last:mb-0">
                                    <div className="text-[12px] font-bold uppercase mb-1">{proj.name}</div>
                                    <p className="text-[11px] text-gray-600">{proj.description}</p>
                                </div>
                            ))}
                        </div>
                    )}
                </div>
            </div>
        </div>
    );

    const renderMinimal = () => (
        <div className="bg-white w-full max-w-[800px] aspect-[1/1.41] shadow-2xl p-20 font-sans text-stone-800 overflow-hidden flex flex-col mx-auto">
            <div className="mb-16">
                <h1 className="text-3xl font-light tracking-[0.1em] uppercase mb-4">{data.personalInfo.fullName || 'YOUR NAME'}</h1>
                <div className="text-[9px] font-medium text-stone-400 space-x-4 uppercase tracking-widest">
                    <span>{data.personalInfo.email}</span>
                    <span>{data.personalInfo.phone}</span>
                    <span>{data.personalInfo.location}</span>
                </div>
            </div>

            <div className="flex flex-col gap-12">
                {hasExperience && (
                    <section>
                        <h4 className="text-[10px] uppercase tracking-widest font-black mb-8 border-b-2 border-stone-100 pb-2">Experience</h4>
                        <div className="flex flex-col gap-8">
                            {data.experience.map((exp, i) => exp.company && (
                                <div key={i} className="grid grid-cols-[120px_1fr] gap-4">
                                    <span className="text-[9px] font-bold text-stone-400 mt-1 uppercase">{exp.date}</span>
                                    <div>
                                        <div className="text-[13px] font-bold mb-1">{exp.company}</div>
                                        <div className="text-[11px] italic mb-3">{exp.role}</div>
                                        <p className="text-[11px] text-stone-500 leading-relaxed font-light">{exp.description}</p>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </section>
                )}

                {hasEducation && (
                    <section>
                        <h4 className="text-[10px] uppercase tracking-widest font-black mb-6 border-b-2 border-stone-100 pb-2">Education</h4>
                        {data.education.map((edu, i) => edu.school && (
                            <div key={i} className="grid grid-cols-[120px_1fr] gap-4 mb-4">
                                <span className="text-[9px] font-bold text-stone-400 mt-1 uppercase">{edu.date}</span>
                                <div>
                                    <div className="text-[12px] font-bold">{edu.school}</div>
                                    <div className="text-[11px] text-stone-500">{edu.degree}</div>
                                </div>
                            </div>
                        ))}
                    </section>
                )}
            </div>
        </div>
    );

    return (
        <div className="kn-page flex flex-col items-center pb-32">
            <div className="kn-context-header w-full max-w-4xl flex justify-between items-center mb-12">
                <div>
                    <h1>Resume Preview</h1>
                    <p>Verified professional high-fidelity output.</p>
                </div>
                <div className="flex gap-4">
                    <Link to="/builder" className="kn-btn kn-btn-secondary">
                        <ArrowLeft className="w-4 h-4 mr-2" />
                        Back to Editor
                    </Link>
                    <button className="kn-btn kn-btn-primary" onClick={() => window.print()}>
                        <Printer className="w-4 h-4 mr-2" />
                        Print / Download
                    </button>
                </div>
            </div>

            {/* Template Selector Tabs */}
            <div className="w-full max-w-4xl px-10 mb-10">
                <div className="flex items-center gap-4 border-b border-gray-200 bg-white/50 p-1 px-4 rounded-t-lg">
                    <div className="flex items-center gap-2 text-gray-400 mr-4 py-4">
                        <Layout className="w-4 h-4" />
                        <span className="text-xs font-black uppercase tracking-widest">Select Template</span>
                    </div>
                    {templates.map(t => (
                        <button
                            key={t.id}
                            className={`py-4 px-6 text-xs font-black uppercase tracking-[0.15em] transition-all border-b-2 ${data.template === t.id
                                ? 'border-red-800 text-red-800'
                                : 'border-transparent text-gray-400 hover:text-gray-900'
                                }`}
                            onClick={() => updateTemplate(t.id)}
                        >
                            {t.label}
                        </button>
                    ))}
                </div>
            </div>

            {/* Layout Switcher */}
            <div className="w-full">
                {data.template === 'classic' && renderClassic()}
                {data.template === 'modern' && renderModern()}
                {data.template === 'minimal' && renderMinimal()}
            </div>
        </div>
    );
};
